'\" 
.\"     Title: immio
.\"    Author: [Sam Stuewe]
.\"      Date: 2013-08-02
.\"  Language: English
.\"
.TH "IMMIO" "1" "2013-08-02" "\ \& 0\&.1" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.\"
.\" <- Main Content ->
.SH "NAME"
immio \- command-line image uploader
.SH "SYNOPSIS"
.sp
immio [\-h|\-\-help] [\-d|\-\-direct] <file1 [file2 ... fileN]>
.sp
.RS 4
\-d,  \-\-direct     post direct links to images instead
                  of landing pages
.RE
.SH "SEE ALSO"
\fBcurl\fR(1)
